var sweety="Sweety";
var cutie="Cutie";
console.log("Before swapping");
console.log(sweety , cutie);
var temp="sweety";
sweety=cutie;
cutie=temp;
console.log("After swapping");
console.log(sweety , cutie);
var num1="100",num2="200",num3="300";
console.log("Before swapping");
console.log(num1,num2,num3);
var file=num1;
num1=num2;
num2=num3;
num3=file;
console.log("After swapping");
console.log(num1,num2,num3);
